# Generated by Django 5.2.7 on 2026-01-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('admin', 'Admin'), ('Chairperson', 'Chairperson'), ('Secretary', 'Secretary'), ('Accountant', 'Accountant'), ('Member', 'Member'), ('priest', 'Priest'), ('catechist', 'Catechist'), ('member', 'Member')], default='Member', max_length=50),
        ),
    ]
