# Generated by Django 5.2.7 on 2026-01-16 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacrament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('baptism', 'Baptism'), ('confirmation', 'Confirmation'), ('eucharist', 'First Holy Communion'), ('reconciliation', 'Reconciliation'), ('marriage', 'Marriage'), ('holy_orders', 'Holy Orders'), ('anointing_sick', 'Anointing of the Sick')], max_length=50, unique=True)),
                ('requires_baptism_certificate', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('min_age', models.IntegerField(blank=True, help_text='Minimum age required', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatechesisMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='certificates/birth/')),
                ('baptism_certificate', models.FileField(blank=True, null=True, upload_to='certificates/baptism/')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='SacramentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_requests', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacrament_requests', to='catechesis.catechesismember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('sacrament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catechesis.sacrament')),
            ],
            options={
                'ordering': ['-request_date'],
                'unique_together': {('member', 'sacrament')},
            },
        ),
    ]
