# Generated by Django 5.2.7 on 2026-01-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('OFFERING', 'Offering'), ('OFFERING_GRATITUDE', 'Offering_gratitude'), ('TITHE', 'Tithe'), ('OTHERS', 'Others')], max_length=57),
        ),
    ]
