# Generated by Django 5.2.7 on 2025-10-26 08:17

import django.db.models.deletion
import member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('leader', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shepherd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardians_name', models.CharField(blank=True, max_length=255, null=True)),
                ('new_believer_school', models.BooleanField()),
                ('pays_tithe', models.BooleanField(default=False)),
                ('working', models.BooleanField(default=False)),
                ('schooling', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=member.models.upload_image_path)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.ministry')),
                ('shepherd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.shepherd')),
            ],
        ),
    ]
