# Generated by Django 5.2.7 on 2026-01-06 18:03

import django.db.models.deletion
import member.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('leader', models.CharField(choices=[('CHAIR PERSON', 'chair person'), ('VICE CHAIR', 'vice chair'), ('SECRETARY', 'secretary'), ('VICE SECRETARY', 'vice secretary'), ('ACCOUNTANT', 'accountant')], max_length=255, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=255, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='TestDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.TextField(help_text='001PT', null=True)),
                ('active', models.BooleanField(default=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(help_text=' Eg. +255 ', max_length=255, null=True, region=None)),
                ('location', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardians_name', models.CharField(blank=True, max_length=255, null=True)),
                ('new_believer_school', models.BooleanField()),
                ('pays_tithe', models.BooleanField(default=False)),
                ('working', models.BooleanField(default=False)),
                ('schooling', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=member.models.upload_image_path)),
                ('shepherd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.community')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.ministry')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('leader', models.CharField(choices=[('CHAIR PERSON', 'chair person'), ('VICE CHAIR', 'Vice Chair'), ('SECRETARY', 'Secretary'), ('VICE SECRETARY', 'Vice Secretary'), ('ACCOUNTANT', 'Accountant'), ('CHAIRPERSON', 'Chairperson')], max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None)),
                ('community_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='member.community')),
            ],
            options={
                'unique_together': {('community_name', 'leader')},
            },
        ),
    ]
