# Generated by Django 5.2.7 on 2026-01-15 16:55

import django.db.models.deletion
import django.utils.timezone
import member.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feast_name', models.TextField(blank=True, max_length=10, null=True)),
                ('feast_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ministries',
            },
        ),
        migrations.CreateModel(
            name='TestDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('leader', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('feast_name', models.TextField(blank=True, max_length='10', null=True)),
                ('feast_date', models.DateField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None)),
                ('community_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='member.community')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.TextField(help_text='001PT', null=True)),
                ('active', models.BooleanField(default=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(help_text=' Eg. +255 ', max_length=255, null=True, region=None)),
                ('location', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardians_name', models.CharField(blank=True, max_length=255, null=True)),
                ('new_believer_school', models.BooleanField()),
                ('pays_tithe', models.BooleanField(default=False)),
                ('working', models.BooleanField(default=False)),
                ('schooling', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=member.models.upload_image_path)),
                ('transfered', models.BooleanField(blank=True, max_length=250, null=True)),
                ('transfer_update', models.CharField(blank=True, max_length=250, null=True)),
                ('shepherd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.community')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.ministry')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commitee_name', models.CharField(max_length=250, null=True)),
                ('position', models.CharField(blank=True, choices=[('VICE CHAIR', 'Vice Chair'), ('SECRETARY', 'Secretary'), ('VICE SECRETARY', 'Vice Secretary'), ('ACCOUNTANT', 'Accountant'), ('CHAIRPERSON', 'Chairperson'), ('MEMBER', 'Member')], max_length=50, null=True)),
                ('description', models.CharField(blank=True, help_text='Write the Functions of your commitee ', max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text=' Eg. +255 ', max_length=255, null=True, region=None)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='commitee_names')),
            ],
        ),
        migrations.CreateModel(
            name='MinistryLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=250)),
                ('position', models.CharField(choices=[('CHAIR PERSON', 'Chair Person'), ('VICE CHAIR', 'Vice Chair'), ('SECRETARY', 'Secretary'), ('VICE SECRETARY', 'Vice Secretary'), ('ACCOUNTANT', 'Accountant'), ('COORDINATOR', 'Coordinator')], max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_date', models.DateField(blank=True, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministry_leaders', to='member.community', verbose_name='Community')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='member.ministry')),
            ],
            options={
                'ordering': ['ministry', 'position'],
                'unique_together': {('ministry', 'position')},
            },
        ),
    ]
