# Generated by Django 5.2.7 on 2025-11-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='code',
            field=models.TextField(help_text='001PT', null=True),
        ),
    ]
