# Generated by Django 5.2.7 on 2025-11-27 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityLeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('leader', models.CharField(choices=[('VICE CHAIR', 'vice chair'), ('SECRETARY', 'secretary'), ('VICE SECRETARY', 'vice secretary'), ('ACCOUNTANT', 'accountant')], max_length=255, null=True)),
                ('phone', models.PositiveIntegerField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ministry',
            name='phone',
            field=models.PositiveIntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='leader',
            field=models.CharField(choices=[('VICE CHAIR', 'vice chair'), ('SECRETARY', 'secretary'), ('VICE SECRETARY', 'vice secretary'), ('ACCOUNTANT', 'accountant')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='shepherd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.communityleaders'),
        ),
        migrations.DeleteModel(
            name='Shepherd',
        ),
    ]
