# Generated by Django 5.2.7 on 2026-01-07 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_ministry_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityleader',
            name='leader',
            field=models.OneToOneField(blank=True, choices=[('CHAIR PERSON', 'chair person'), ('VICE CHAIR', 'Vice Chair'), ('SECRETARY', 'Secretary'), ('VICE SECRETARY', 'Vice Secretary'), ('ACCOUNTANT', 'Accountant'), ('CHAIRPERSON', 'Chairperson')], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='member.member'),
        ),
    ]
