# Generated by Django 5.2.7 on 2025-11-27 17:50

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_communityleaders_ministry_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=255, null=True, region=None),
        ),
    ]
