# Generated by Django 5.2.7 on 2026-01-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_communityleader_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='position',
            field=models.CharField(blank=True, choices=[('CHAIR PERSON', 'chair person'), ('VICE CHAIR', 'vice chair'), ('SECRETARY', 'secretary'), ('VICE SECRETARY', 'vice secretary'), ('ACCOUNTANT', 'accountant')], max_length=30, null=True),
        ),
    ]
