# Generated by Django 5.2.7 on 2026-01-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_ministry_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='transfer_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='transfer_update',
            field=models.BooleanField(blank=True, max_length=250, null=True),
        ),
    ]
