# Generated by Django 5.2.7 on 2025-11-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_ministry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityleaders',
            name='phone',
            field=models.PositiveIntegerField(help_text=' Eg. +255 ', max_length=255, null=True),
        ),
    ]
