# Generated by Django 5.2.7 on 2026-01-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_transfer_type_member_transfer_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='transfer_type',
        ),
        migrations.AddField(
            model_name='member',
            name='transfered',
            field=models.BooleanField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='transfer_update',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
