# Generated by Django 5.2.7 on 2025-11-27 20:33

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_communityleaders_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('leader', models.CharField(choices=[('VICE CHAIR', 'vice chair'), ('SECRETARY', 'secretary'), ('VICE SECRETARY', 'vice secretary'), ('ACCOUNTANT', 'accountant')], max_length=255, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='+255', max_length=255, null=True, region=None)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=models.PositiveIntegerField(help_text=' Eg. +255 ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='shepherd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.communityleader'),
        ),
        migrations.DeleteModel(
            name='CommunityLeaders',
        ),
    ]
