# Generated by Django 5.2.7 on 2025-11-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_communityleader_alter_member_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityleader',
            name='community_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communityleader',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
