# Generated by Django 5.2.7 on 2026-01-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_remove_member_transfer_type_member_transfered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='leader',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
