# Generated by Django 5.2.7 on 2026-01-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_ministry_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityleader',
            name='leader',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
