# Generated by Django 5.2.7 on 2025-11-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_communityleader_community_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='leader',
            field=models.CharField(choices=[('CHAIR PERSON', 'chair person'), ('VICE CHAIR', 'vice chair'), ('SECRETARY', 'secretary'), ('VICE SECRETARY', 'vice secretary'), ('ACCOUNTANT', 'accountant')], max_length=255, null=True),
        ),
    ]
