# Generated by Django 5.2.7 on 2026-01-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_communityleader_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='description',
        ),
        migrations.AddField(
            model_name='ministry',
            name='description',
            field=models.ManyToManyField(blank=True, null=True, to='member.community', verbose_name='Community_member'),
        ),
    ]
