# Generated by Django 5.2.7 on 2025-11-28 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_ministry_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='communityleader',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='communityleader',
            name='leader',
            field=models.CharField(choices=[('CHAIR PERSON', 'chair person'), ('VICE CHAIR', 'Vice Chair'), ('SECRETARY', 'Secretary'), ('VICE SECRETARY', 'Vice Secretary'), ('ACCOUNTANT', 'Accountant'), ('CHAIRPERSON', 'Chairperson')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communityleader',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communityleader',
            name='community_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='member.community'),
        ),
        migrations.AlterUniqueTogether(
            name='communityleader',
            unique_together={('community_name', 'leader')},
        ),
    ]
