# Generated by Django 5.2.7 on 2025-12-01 02:53

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_community_alter_communityleader_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityleader',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text=' Eg. +255 ', max_length=255, null=True, region=None),
        ),
    ]
