# Generated by Django 5.2.7 on 2026-01-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_remove_ministry_description_ministry_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='description',
        ),
        migrations.AddField(
            model_name='ministry',
            name='description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Community_member', to='member.community', verbose_name='Community'),
        ),
    ]
