# Generated by Django 5.2.7 on 2025-12-01 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_alter_communityleader_phone_alter_member_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='shepherd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.community'),
        ),
    ]
