# Generated by Django 5.2.7 on 2026-01-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_ministry_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityleader',
            name='feast_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityleader',
            name='description',
            field=models.TextField(blank=True, max_length='10', null=True),
        ),
    ]
