# Generated by Django 5.2.7 on 2026-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_communityleader_feast_name_ministry_feast_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='feast_name',
            field=models.TextField(blank=True, max_length='10', null=True),
        ),
    ]
