# Generated by Django 5.2.7 on 2026-01-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_ministry_feast_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Community_member', to='member.community', verbose_name='Community'),
        ),
    ]
