# Generated by Django 5.2.7 on 2026-01-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_alter_ministry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='position',
            field=models.CharField(blank=True, choices=[('CHAIR PERSON', 'chair person'), ('VICE CHAIR', 'vice chair'), ('SECRETARY', 'secretary'), ('VICE SECRETARY', 'vice secretary'), ('ACCOUNTANT', 'accountant'), ('COORDINATOR', 'coordinator')], default='Member', max_length=30, null=True),
        ),
    ]
