# Generated by Django 5.2.7 on 2026-01-13 14:09

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_alter_ministry_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commitee_name', models.CharField(max_length=250, null=True)),
                ('position', models.CharField(blank=True, choices=[('VICE CHAIR', 'Vice Chair'), ('SECRETARY', 'Secretary'), ('VICE SECRETARY', 'Vice Secretary'), ('ACCOUNTANT', 'Accountant'), ('CHAIRPERSON', 'Chairperson')], max_length=50, null=True)),
                ('description', models.CharField(blank=True, help_text='Write the Functions of your commitee ', max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text=' Eg. +255 ', max_length=255, null=True, region=None)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='commitee_names')),
            ],
        ),
    ]
