# Generated by Django 5.2.7 on 2026-01-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_commitee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commitee',
            new_name='Committee',
        ),
    ]
