# Generated by Django 5.2.7 on 2026-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_rename_commitee_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='position',
            field=models.CharField(blank=True, choices=[('VICE CHAIR', 'Vice Chair'), ('SECRETARY', 'Secretary'), ('VICE SECRETARY', 'Vice Secretary'), ('ACCOUNTANT', 'Accountant'), ('CHAIRPERSON', 'Chairperson'), ('MEMBER', 'Member')], max_length=50, null=True),
        ),
    ]
