# Generated by Django 5.2.7 on 2026-01-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_alter_committee_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityleader',
            unique_together=set(),
        ),
    ]
