# Generated by Django 5.2.7 on 2026-01-06 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TithePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sms_failure_count', models.IntegerField(default=0)),
                ('last_sms_error', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invoice Date')),
                ('contact_number', models.CharField(max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='TitheReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('print_attempts', models.IntegerField(default=0)),
                ('last_print_error', models.TextField(blank=True, null=True)),
                ('church_name', models.CharField(default='Your Church Name', max_length=255)),
                ('church_address', models.TextField(default='Your Church Address')),
                ('church_phone', models.CharField(default='+255 XXX XXX XXX', max_length=20)),
                ('tithe_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='tithe.tithepayment')),
            ],
            options={
                'verbose_name': 'Tithe Receipt',
                'verbose_name_plural': 'Tithe Receipts',
                'ordering': ['-generated_at'],
            },
        ),
    ]
