# Generated by Django 5.2.7 on 2025-11-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tithe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tithepayment',
            name='last_sms_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tithepayment',
            name='sms_failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tithepayment',
            name='sms_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tithepayment',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tithepayment',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
