# Generated by Django 5.2.7 on 2025-11-29 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tithe', '0002_tithepayment_last_sms_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitheReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('print_attempts', models.IntegerField(default=0)),
                ('last_print_error', models.TextField(blank=True, null=True)),
                ('church_name', models.CharField(default='Your Church Name', max_length=255)),
                ('church_address', models.TextField(default='Your Church Address')),
                ('church_phone', models.CharField(default='+255 XXX XXX XXX', max_length=20)),
                ('tithe_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='tithe.tithepayment')),
            ],
            options={
                'verbose_name': 'Tithe Receipt',
                'verbose_name_plural': 'Tithe Receipts',
                'ordering': ['-generated_at'],
            },
        ),
    ]
